import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {createHash} from 'node:crypto';import {fileURLToPath} from 'node:url';import * as IO from '../js/io.js';import {detectPreset} from '../js/presets.js';
// Immutable native exports from a deliberately fictional Bluecoins book.
const sha=b=>createHash('sha256').update(b).digest('hex');
const proof={fixtures:[{file:"actual-owned-myr-expense.csv",path:fileURLToPath(new URL("./fixtures/bluecoins-device-owned-expense.csv",import.meta.url)),sha256:"e0f2e5b1c17b3d7a0e415f3c555ebf2ccb43d3c2bdd58e8bacffe64874bd02ec"},{file:"actual-owned-myr-transfer-photo.csv",path:fileURLToPath(new URL("./fixtures/bluecoins-device-owned-transfer-photo.csv",import.meta.url)),sha256:"229c2f8e949a966adb6c725afab73defb58dc5920c1693708b0a085eb140ea6c"}]};
for(const f of proof.fixtures)assert.equal(sha(readFileSync(f.path)),f.sha256);
function run(file,modify=x=>x,overrides={}){const rows=IO.parseCSV(IO.decodeBytes(Buffer.from(modify(readFileSync(proof.fixtures.find(f=>f.file===file).path).toString('utf8'))))),h=IO.headerRow(rows),header=rows[h],body=rows.slice(h+1),preset=detectPreset(header,file);assert.equal(preset.id,'bluecoins');const {names}=IO.accountNames(body,preset.map,{preset,header}),accounts=Object.fromEntries(names.map(n=>[n.toLowerCase(),n.toLowerCase()]));return {...IO.rowsToTx(body,preset.map,{header,preset,accounts,accountId:'default',strictCurrency:true,now:1,...overrides}),preset,header,body};}
test('actual Bluecoins source parent and child columns both survive',()=>{const r=run('actual-owned-myr-transfer-photo.csv'),x=r.txs.find(x=>x.type==='expense');assert.equal(r.preset.map.category,7);assert.equal(r.preset.map.sub,8);assert.equal(IO.rowCategory(r.body[2],r.preset.map,{preset:r.preset,header:r.header}),'Entertainment');assert.deepEqual([x.category,x.sub,x.amount,x.date,x.time,x.accountId],['fun','Dining Out',600,'2026-10-04','12:03','wallet']);});
test('ordinary review can retain exact original parent name or deliberately remap it',()=>{const x=run('actual-owned-myr-transfer-photo.csv',x=>x,{catMap:{Entertainment:'new:Entertainment'}}).txs.find(x=>x.type==='expense');assert.deepEqual([x.category,x.sub],['new:Entertainment','Dining Out']);const changed=run('actual-owned-myr-transfer-photo.csv',x=>x,{catMap:{Entertainment:'dining'}}).txs.find(x=>x.type==='expense');assert.deepEqual([changed.category,changed.sub],['dining','Dining Out']);});
test('actual paired transfer stays one200sen transfer with no parent or child spending metadata',()=>{const r=run('actual-owned-myr-transfer-photo.csv'),x=r.txs.find(x=>x.type==='transfer');assert.equal(r.txs.length,2);assert.equal(r.transfers,1);assert.deepEqual([x.accountId,x.toAccountId,x.amount],['wallet','checking',200]);assert.equal(x.sub,undefined);assert.equal(r.txs.filter(x=>x.type==='expense').reduce((n,x)=>n+x.amount,0),600);});
test('initial actual Others parent and child remain under Other',()=>{const x=run('actual-owned-myr-expense.csv').txs[0];assert.deepEqual([x.category,x.sub,x.amount],['other','Others',600]);});
test('foreign actual-file mutation remains refused without currency relabelling',()=>{const r=run('actual-owned-myr-transfer-photo.csv',x=>x.replaceAll('"MYR"','"GBP"'));assert.equal(r.txs.length,0);assert.equal(r.skipped.length,3);assert.ok(r.skipped.every(s=>s.why==='currency'));});
test('Tally CSV and standard JSON retain the actual mapped parent and child',()=>{const x=run('actual-owned-myr-transfer-photo.csv').txs.find(x=>x.type==='expense'),accounts=[{id:'wallet',name:'Wallet',kind:'cash',opening:0}],csv=IO.parseCSV(IO.toCSV([x],accounts)),h=IO.headerRow(csv),preset=detectPreset(csv[h],'tally.csv');const r=IO.rowsToTx(csv.slice(h+1),preset.map,{preset,header:csv[h],accountId:'wallet',accounts:{wallet:'wallet'}});assert.deepEqual([r.txs[0].category,r.txs[0].sub],['fun','Dining Out']);const backup=IO.readBackup(IO.makeBackup({accounts,tx:[x],recurring:[],kv:{}}));assert.deepEqual([backup.tx[0].category,backup.tx[0].sub,backup.tx[0].amount],['fun','Dining Out',600]);});
test('clearing the mapped child is respected, without changing the selected parent',()=>{const rows=IO.parseCSV(IO.decodeBytes(readFileSync(proof.fixtures[1].path))),h=IO.headerRow(rows),preset=detectPreset(rows[h],'b.csv'),map={...preset.map};delete map.sub;const r=IO.rowsToTx(rows.slice(h+1),map,{preset,header:rows[h],accounts:{wallet:'wallet',checking:'checking'}});assert.equal(r.txs.find(x=>x.type==='expense').sub,undefined);assert.equal(r.txs.find(x=>x.type==='expense').category,'fun');});
test('synthetic marker regression keeps transfer detection on source Category despite a blank parent group',()=>{const r=run('actual-owned-myr-transfer-photo.csv',x=>x.replaceAll('"Transfer",','"Expense",').replaceAll('"(Transfer)","(Transfer)"','"","(Transfer)"'));assert.equal(r.transfers,1);assert.equal(r.txs.filter(x=>x.type==='transfer').length,1);assert.equal(r.txs.filter(x=>x.type==='expense').reduce((n,x)=>n+x.amount,0),600);});
