import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {mergeSections,sections,cropPixels} from '../js/receipt-image.js';import {reading} from '../js/receipt-read.js';
const trace=JSON.parse(readFileSync(new URL('./fixtures/ocr-owned-seams.json',import.meta.url))),expected=trace.fixture.items,norm=s=>String(s||'').replace(/\s/gu,'').toUpperCase();
test('actual owned clear OCR seam coordinates produce24 exact ordered name/amount tuples',()=>{const r=trace.runs.find(r=>r.kind==='long'),passes=r.timings.find(t=>t.stage==='worker').passes,areas=sections(1000,2800),groups=passes.map((p,i)=>({area:areas[i],texts:p.syntheticBoxes})),got=reading(mergeSections(groups)).receipt;assert.equal(got.items.length,24);assert.deepEqual(got.items.map(i=>[norm(i.name),i.cents]),expected.map(i=>[norm(i.name),i.cents]));assert.equal(got.total,53760);});
test('actual accepted90-degree rotation seam boxes retain24 exact name/amount tuples',()=>{const r=trace.runs.find(r=>r.kind==='rotated');assert.equal(r.turns,3);const passes=r.timings.find(t=>t.stage==='worker').passes.slice(-2),areas=sections(1000,2800),got=reading(mergeSections(passes.map((p,i)=>({area:areas[i],texts:p.syntheticBoxes})))).receipt;assert.deepEqual(got.items.map(i=>[norm(i.name),i.cents]),expected.map(i=>[norm(i.name),i.cents]));assert.equal(got.total,53760);});
const line=(text,y,mean=.99)=>({text,mean,box:[[60,y],[960,y],[960,y+33],[60,y+33]]});
test('weaker match is cross-crop and same complete content only; repeated real rows retained',()=>{const first={x:0,y:0,w:1000,h:2000},second={x:0,y:1800,w:1000,h:1000};const row=line('OWNED ITEM 28.90',1826),duplicate=line('OWNEDITEM 28.90',12);assert.equal(mergeSections([{area:first,texts:[row]},{area:second,texts:[duplicate]}]).length,1);assert.equal(mergeSections([{area:first,texts:[row,line('OWNED ITEM 28.90',1812)]}]).length,2);assert.equal(mergeSections([{area:first,texts:[row]},{area:second,texts:[line('OWNED ITEM 29.90',12)]}]).length,2);assert.equal(mergeSections([{area:first,texts:[row,line('OWNED ITEM 28.90',1906)]},{area:second,texts:[duplicate,line('OWNEDITEM 28.90',92)]}]).length,2);});
test('ambiguous nearby/tall/partial lines and nonoverlapping crops never gain weaker dedup',()=>{const first={x:0,y:0,w:1000,h:2000},second={x:0,y:1800,w:1000,h:1000};assert.equal(mergeSections([{area:first,texts:[line('OWNED ITEM 28.90',1826)]},{area:second,texts:[line('OWNED ITEM 28.90',50)]}]).length,2);assert.equal(mergeSections([{area:first,texts:[line('OWNED ITEM 28.90',1826)]},{area:second,texts:[line('OWNED ITEM',12)]}]).length,2);const distant={x:0,y:2200,w:1000,h:1000};assert.equal(mergeSections([{area:first,texts:[line('OWNED ITEM 28.90',1826)]},{area:distant,texts:[line('OWNED ITEM 28.90',-388)]}]).length,2);});
test('an incumbent strict match wins over earlier weaker candidates; ambiguous weaker matches retain boxes',()=>{const first={x:0,y:0,w:1000,h:2000},second={x:0,y:1800,w:1000,h:1000};const exact=mergeSections([{area:first,texts:[line('OWNED ITEM 28.90',1826,.8),line('OWNED ITEM 28.90',1848,.8)]},{area:second,texts:[line('OWNED ITEM 28.90',40,.99)]}]);assert.equal(exact.length,2);assert.equal(exact[0].box[0][1],1826);assert.equal(exact[1].box[0][1],1840);const ambiguous=mergeSections([{area:first,texts:[line('OWNED ITEM 28.90',1826),line('OWNED ITEM 28.90',1854)]},{area:second,texts:[line('OWNED ITEM 28.90',40)]}]);assert.equal(ambiguous.length,3);const noAmount=mergeSections([{area:first,texts:[line('OWNED ITEM',1826)]},{area:second,texts:[line('OWNEDITEM',12)]}]);assert.equal(noAmount.length,2);});

test('2800px24-item receipt uses200px overlap and shorter tail instead of1200px duplication',()=>{const s=sections(1000,2800);assert.deepEqual(s,[{x:0,y:0,w:1000,h:2000},{x:0,y:1800,w:1000,h:1000}]);assert.equal(s.reduce((n,x)=>n+x.w*x.h,0),3e6);});
test('vertical/horizontal clear,difficult,boundary and max-size inputs keep every pixel, fixed overlap, cap',()=>{for(const long of [1,1999,2000,2001,2199,2200,2800,3200,3600,3800,3801,7300,12000,20000])for(const orientation of [true,false]){const w=orientation?1000:long,h=orientation?long:1000,s=sections(w,h),vertical=h>=w,end=vertical?'y':'x',length=vertical?'h':'w';assert.equal(s[0][end],0);assert.equal(s.at(-1)[end]+s.at(-1)[length],Math.max(w,h));assert.ok(s.length<=12);for(let i=1;i<s.length;i++){assert.equal(s[i-1][end]+s[i-1][length]-s[i][end],200);assert.ok(s[i][length]>0&&s[i][length]<=2000);}}assert.throws(()=>sections(1000,50000),/Too many/);});
test('a printed band at a crop seam is wholly available in an adjacent crop, including one-pixel tails',()=>{for(const long of [2000,2001,2800,3600,3800,3801])for(const horizontal of [false,true]){const s=sections(horizontal?long:1000,horizontal?1000:long),axis=horizontal?'x':'y',size=horizontal?'w':'h';for(const area of s)for(const edge of [area[axis],area[axis]+area[size]])for(const height of [1,40,199,200])for(const offset of [-height,-1,0,1]){const top=edge+offset,bottom=top+height;if(top<0||bottom>long)continue;assert.ok(s.some(a=>a[axis]<=top&&a[axis]+a[size]>=bottom),`band ${top}..${bottom} missing at length${long}`);}}});
test('last-tail actual crop bytes preserve geometry and repeated source rows deduplicate by position only',()=>{const raw={width:2,height:2800,data:new Uint8ClampedArray(2*2800*4)};for(let y=0;y<2800;y++)raw.data[(y*2)*4]=y%256;const a=sections(2,2800)[1],tail=cropPixels(raw,a);assert.equal(tail.height,1000);assert.equal(tail.data[0],1800%256);assert.equal(tail.data[(999*2)*4],2799%256);const row=y=>({text:'OWNED SAME ITEM',mean:.99,box:[[0,y],[20,y],[20,y+10],[0,y+10]]});const groups=[{area:{x:0,y:0},texts:[row(1900),row(1950)]},{area:{x:0,y:1800},texts:[row(100),row(150),row(220)]}];assert.equal(mergeSections(groups).length,3);});
