import test from 'node:test';import assert from 'node:assert/strict';import{webcrypto}from'node:crypto';import { indexedDB } from './fixtures/idbshim.mjs';
globalThis.crypto ||= webcrypto;globalThis.indexedDB=indexedDB;
const st=await import('../js/state.js'),db=await import('../js/db.js'),IO=await import('../js/io.js'),M2=await import('../js/money2time.js');await st.load();
const account={id:'a',name:'Cash',kind:'cash',opening:0,createdAt:1700000000000},row={id:'old',accountId:'a',type:'expense',amount:100,date:'2026-10-01',category:'dining'};
async function seed(){await st.replaceAll({accounts:[account],tx:[row],recurring:[],kv:{settings:{onboarded:true},customCats:[],subcats:{}}});}
const incoming={accounts:[{...account,id:'new'}],tx:[{...row,id:'newtx',accountId:'new'}],recurring:[],kv:{settings:{onboarded:true},customCats:[],subcats:{}}};
test('own backup preserves boolean typed false/true and omits untrusted nonbooleans without changing backdated balance semantics',()=>{
 const accounts=[{...account,id:'unset',typed:false},{...account,id:'set',typed:true,updatedAt:Date.parse('2026-10-04T00:00:00Z')},{...account,id:'legacy'},{...account,id:'null',typed:null},{...account,id:'string',typed:'false'}],restored=IO.readBackup(IO.makeBackup({accounts,tx:[],recurring:[],kv:{}}));
 assert.equal(restored.accounts[0].typed,false);assert.equal(restored.accounts[1].typed,true);for(const a of restored.accounts.slice(2))assert.equal(Object.hasOwn(a,'typed'),false);
 const old=[{...row,id:'one',accountId:'unset'},{...row,id:'two',accountId:'set'}];assert.deepEqual(IO.typedShift(restored.accounts,[],old,'2026-10-04'),IO.typedShift(accounts,[],old,'2026-10-04'));
});
test('Money2Time converted custom categories/subcategories survive a full Tally backup reader roundtrip',()=>{
 const id='00000001-0000-0000-0000-000000000000',category='00000002-0000-0000-0000-000000000000',child='00000003-0000-0000-0000-000000000000',tx='00000004-0000-0000-0000-000000000000';
 const tables=Object.fromEntries(['accounts','account_groups','categories','transactions','transaction_splits','exchange_rates','recurring_rules','settings','monthly_wage_settings','albums','album_transactions','items','budget_templates','budget_template_categories','monthly_budgets','monthly_budget_categories','receipt_splits','receipt_split_items','receipt_split_item_shares'].map(k=>[k,[]]));
 tables.accounts=[{id,name:'Cash',type:'debit',currency:'MYR',starting_balance:0,created_at:'2026-10-04T00:00:00Z'}];tables.categories=[{id:category,name:'Source custom',type:'expense',parent_id:null},{id:child,name:'Child',type:'expense',parent_id:category}];tables.transactions=[{id:tx,account_id:id,category_id:child,type:'expense',amount:6,currency:'MYR',date:'2026-10-04T00:00:00Z',created_at:'2026-10-04T00:00:00Z'}];
 const converted=M2.readMoney2Time({version:3,exportedAt:'2026-10-04T00:00:00Z',tables,userAssets:[]}),restored=IO.readBackup(IO.makeBackup({...converted,recurring:[],kv:{customCats:converted.customCats,subcats:converted.subcats}}));
 assert.equal(converted.customCats[0].id.length,40);assert.match(converted.customCats[0].id,/^c_/);assert.deepEqual(restored.kv.customCats,converted.customCats);assert.equal(restored.tx[0].category,converted.tx[0].category);assert.equal(restored.tx[0].sub,'Child');assert.deepEqual(restored.kv.subcats,JSON.parse(JSON.stringify(converted.subcats)));
});
test('replace restore refuses a changed existing row and keeps current book and photos intact',async()=>{await seed();const guard=await st.restoreSnapshot();await db.put('tx',{...row,amount:200});await assert.rejects(st.replaceAll({...incoming,...guard}),e=>e.code==='STALE');assert.equal((await db.get('tx','old')).amount,200);assert.equal(await db.get('tx','newtx'),null);});
test('replace restore key-set guards refuse newly added rows absent from the preparation snapshot',async()=>{await seed();const guard=await st.restoreSnapshot();await db.put('tx',{...row,id:'pc-new',amount:300});await assert.rejects(st.replaceAll({...incoming,...guard}),e=>e.code==='STALE');assert.ok(await db.get('tx','pc-new'));assert.equal(await db.get('tx','newtx'),null);});
test('merge restore refuses changed settings and missing original records rather than overwriting them',async()=>{await seed();const guard=await st.restoreSnapshot();await db.put('kv',{key:'settings',value:{onboarded:true,lang:'ja'}});await assert.rejects(st.addAll({...incoming,...guard}),e=>e.code==='STALE');assert.equal((await db.getKv('settings')).lang,'ja');await seed();const next=await st.restoreSnapshot();await db.delMany('tx',['old']);await assert.rejects(st.addAll({...incoming,...next}),e=>e.code==='STALE');});
test('restore snapshot and atomic generation guard refuse a replaced book even when row IDs are identical',async()=>{await seed();const guard=await st.restoreSnapshot();await st.replaceAll({accounts:[account],tx:[row],recurring:[],kv:{settings:{onboarded:true}}});await assert.rejects(st.replaceAll({...incoming,...guard}),e=>e.code==='STALE');assert.equal(await db.get('tx','newtx'),null);});
test('cancellation immediately before transaction creation saves neither ledger nor photo',async()=>{await seed();const guard=await st.restoreSnapshot();await assert.rejects(st.replaceAll({...incoming,...guard,receipts:[{id:'receipt',blob:new Blob(['owned fixture'])}],beforeWrite:()=>{throw Object.assign(Error('Cancelled'),{cancelled:true});}}),e=>e.cancelled===true);assert.ok(await db.get('tx','old'));assert.equal(await db.get('receipts','receipt'),null);});
test('guarded successful replace keeps ledger and receipt atomic, and absent legacy generation can be snapshotted',async()=>{await seed();const guard=await st.restoreSnapshot();await st.replaceAll({...incoming,...guard,receipts:[{id:'receipt',blob:new Blob(['owned fixture'])}]});assert.ok(await db.get('tx','newtx'));assert.equal(await(await db.get('receipts','receipt')).blob.text(),'owned fixture');await db.delMany('kv',['bookGeneration']);await st.load();assert.ok(await st.restoreSnapshot());});
