import {COPY_IDS} from './accessor.mjs';
const fail=(code,paths=[])=>{throw Object.assign(new Error(code==='LOSSY_FORMAT'?'This saved copy has fields the current Tally backup reader cannot preserve.':'Safety export could not complete.'),{code,paths});};
// Check all supplied content, allowing only the normal reader's implicit MYR default.
export function missingFields(expected,actual,path='',out=[]){if(path.match(/^accounts\.\d+\.currency$/)&&expected==='MYR'&&actual===undefined)return out;
 if(expected&&typeof expected==='object'){if(Array.isArray(expected)){if(!Array.isArray(actual)||actual.length!==expected.length){out.push(path);return out;}expected.forEach((v,i)=>missingFields(v,actual[i],`${path}.${i}`,out));}else{if(!actual||typeof actual!=='object'||Array.isArray(actual)){out.push(path);return out;}for(const [k,v]of Object.entries(expected))missingFields(v,actual[k],path?`${path}.${k}`:k,out);}}else if(expected!==actual)out.push(path);return out;}
export function createSafetyExport({access,core,io,authorized,onProgress=()=>{},yieldPaint=()=>new Promise(r=>setTimeout(r,0))}){
 if(!access||!core||!io||['makeBackup','readBackup','unzip','zipStore'].some(k=>typeof io[k]!=='function')||io.BACKUP_JSON!=='tally-backup.json'||[authorized,onProgress,yieldPaint].some(f=>typeof f!=='function'))fail('CONFIG');let epoch=0,busy=false,saving=false,closed=false;
 function check(e){let ok=false;try{ok=authorized()===true;}catch{}if(closed||epoch!==e||!ok)fail('CANCELLED');}
 async function stage(e,stage,counts={}){check(e);await onProgress({stage,...counts});check(e);await yieldPaint();check(e);}
 async function build(input,internal=false){if(!input||Object.getPrototypeOf(input)!==Object.prototype||Object.keys(input).sort().join(',')!=='format,id'||!['zip','json'].includes(input.format)||!COPY_IDS.includes(input.id))fail('SELECTOR');input=Object.freeze({id:input.id,format:input.format});if(busy||saving&&!internal)fail('BUSY');busy=true;const e=epoch;try{
  await stage(e,'reading-copy');const copy=await access.read({id:input.id});check(e);if(copy?.id!==input.id)fail('SELECTOR');const book=core.validateBook(copy.book);if(input.format==='json'&&book.receipts.length)fail('PHOTOS_REQUIRE_ZIP');
  await stage(e,'creating-json');const content={accounts:book.accounts,tx:book.tx,recurring:book.recurring,kv:book.kv},text=io.makeBackup(content),parsed=io.readBackup(text),paths=missingFields(content,{accounts:parsed.accounts,tx:parsed.tx,recurring:parsed.recurring,kv:{...parsed.kv,settings:parsed.settings}});if(parsed.dropped||paths.length)fail('LOSSY_FORMAT',paths);const bytes=new TextEncoder().encode(text);if(bytes.length>16*1024*1024)fail('BOUNDS');check(e);
  let blob;const photos=copy.photos;if(!(photos instanceof Map)||photos.size!==book.receipts.length)fail('RECEIPTS');if(input.format==='json')blob=new Blob([bytes],{type:'application/json'});else{
   const files=[{name:io.BACKUP_JSON,data:bytes}];let done=0,total=bytes.length;await stage(e,'collecting-photos',{completed:done,total:book.receipts.length});for(const m of book.receipts){if(!/^[\w-]{1,60}$/.test(m.id))fail('LOSSY_FORMAT',[`receipts.${m.id}.id`]);const photo=photos.get(m.id);if(!(photo instanceof Blob)||photo.type!==m.mime||photo.size!==m.bytes||photo.size>40*1024*1024||(total+=photo.size)>40*1024*1024)fail('BOUNDS');check(e);const data=new Uint8Array(await photo.arrayBuffer());check(e);await core.verifyReceipt(m,data);check(e);files.push({name:`photos/${m.id}.jpg`,data});await stage(e,'collecting-photos',{completed:++done,total:book.receipts.length});}
   await stage(e,'creating-zip');blob=io.zipStore(files);if(!(blob instanceof Blob)||blob.size>40*1024*1024)fail('BOUNDS');await stage(e,'checking-output');const output=await io.unzip(new Uint8Array(await blob.arrayBuffer()),()=>true,{budget:40*1024*1024,entries:65000});check(e);if(Object.keys(output).length!==files.length||!output[io.BACKUP_JSON])fail('ROUNDTRIP');const restored=io.readBackup(new TextDecoder('utf-8',{fatal:true}).decode(output[io.BACKUP_JSON]));if(restored.dropped||missingFields(content,{accounts:restored.accounts,tx:restored.tx,recurring:restored.recurring,kv:{...restored.kv,settings:restored.settings}}).length)fail('ROUNDTRIP');for(const m of book.receipts){const data=output[`photos/${m.id}.jpg`];if(!data)fail('RECEIPTS');await core.verifyReceipt(m,data);check(e);}
  }
  await stage(e,'ready');return Object.freeze({name:`tally-safety-${input.id}.${input.format}`,mime:input.format==='zip'?'application/zip':'application/json',blob,archiveSha:copy.evidence.archiveSha,revision:copy.evidence.snapshotHash,photos:book.receipts.length,status:'prepared'});
 }finally{busy=false;}}
 // Saving is host-owned. Native must return literal success after actual provider completion.
 async function save(input,{mode,saveToDevice,requestDownload}){if(!['native','browser'].includes(mode)||mode==='native'&&typeof saveToDevice!=='function'||mode==='browser'&&typeof requestDownload!=='function')fail('CONFIG');if(busy||saving)fail('BUSY');saving=true;try{const e=epoch,prepared=await build(input,true);check(e);await stage(e,'saving');if(mode==='native'){const result=await saveToDevice(prepared);if(result!==true)return {status:'not-saved'};return {status:'saved'};}const result=requestDownload(prepared);if(result&&typeof result.then==='function'){Promise.resolve(result).catch(()=>{});fail('DOWNLOAD_CONTRACT');}return {status:result===false?'not-requested':'download-requested'};}finally{saving=false;}}
 function cancel(){epoch++;access.cancel();}function close(){closed=true;cancel();}return Object.freeze({build:input=>build(input),save,cancel,close});
}
