// Local-only presentation. Providers retain all validation and atomic-write authority.
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ids=['current','before','source'];
const names={current:'Saved sync safety copy',before:'Book before replacement',source:'Restored source copy'};
const stages={'reading-copy':'Reading safety copy','checking-archive':'Checking safety archive','checking-photos':'Checking receipt photos','creating-json':'Creating backup data','collecting-photos':'Collecting receipt photos','creating-zip':'Creating backup ZIP','checking-output':'Checking backup ZIP',ready:'Backup ready',saving:'Choose where to save',review:'Preparing replacement review',replace:'Replacing this book'};
export function nativeSaveSucceeded(result){return !!result&&Object.getPrototypeOf(result)===Object.prototype&&Object.keys(result).length===1&&result.cancelled===false;}
export function replacementRows(before,after){const rows=[];for(const kind of ['accounts','tx','recurring','receipts']){const a=new Map(before[kind].map(r=>[r.id,r])),b=new Map(after[kind].map(r=>[r.id,r]));for(const id of [...new Set([...a.keys(),...b.keys()])].sort()){const left=a.get(id)??null,right=b.get(id)??null;if(JSON.stringify(left)!==JSON.stringify(right))rows.push({kind,id,before:left,after:right});}}for(const id of [...new Set([...Object.keys(before.kv),...Object.keys(after.kv)])].sort()){const left=before.kv[id]??null,right=after.kv[id]??null;if(JSON.stringify(left)!==JSON.stringify(right))rows.push({kind:'kv',id,before:left,after:right});}return rows;}
export function createMainSafetyUi({createOperations,authorized,getGeneration,onPrivacyChange,openSheet,closeSheet,t,document:doc,window:win,mode,saveToDevice,requestDownload}){
 if([createOperations,authorized,getGeneration,onPrivacyChange,openSheet,closeSheet,t].some(f=>typeof f!=='function')||!doc||!win||!['native','browser'].includes(mode)||typeof(mode==='native'?saveToDevice:requestDownload)!=='function')throw Error('Missing safety UI provider');
 let session=null,closed=false;
 const permitted=()=>{try{return !closed&&authorized()===true&&doc.hidden===false;}catch{return false;}};
 function current(s){return session===s&&permitted()&&getGeneration()===s.generation&&s.el?.isConnected&&!s.el.closest('.out');}
 function cancel(){const s=session;session=null;if(!s)return;s.operations?.access?.close();s.operations?.restore?.close();s.operations?.exporter?.close();s.stopPrivacy?.();doc.removeEventListener('visibilitychange',s.hidden);doc.removeEventListener('tally:book-replaced',s.replaced);win.removeEventListener('pagehide',s.leave);if(s.el?.isConnected&&!s.el.closest('.out'))closeSheet();}
 function progress(s,event){if(!current(s))return;const label=stages[event.stage];if(!label)return;const counts=Number.isSafeInteger(event.completed)&&Number.isSafeInteger(event.total)&&event.completed>=0&&event.total>=event.completed?` ${event.completed}/${event.total}`:'';s.status=t(label)+counts;const target=s.el.querySelector('[data-safety-status]');if(target)target.textContent=s.status;}
 function html(s){const disabled=s.busy?' disabled':'';return `<h2 class="sh-title">${esc(t('Saved safety copies'))}</h2><p class="sh-body">${esc(t('These copies stay inside Tally. Export a standard backup to keep a separate file.'))}</p><p role="status" aria-live="polite" aria-atomic="true" data-safety-status>${esc(s.status)}</p><div data-safety-content>${s.review?review(s):`<label class="field">${esc(t('Choose a safety copy'))}<select data-safety-select${disabled}>${s.copies.map(r=>`<option value="${esc(r.id)}"${r.id===s.selected?' selected':''}>${esc(t(names[r.id]))}${r.purpose==='unreadable'?` — ${esc(t('Unreadable'))}`:''}</option>`).join('')}</select></label>${s.copies.length?`<div class="row2"><button class="btn" data-safety-action="export"${disabled}>${esc(t('Export backup ZIP'))}</button><button class="btn ghost" data-safety-action="review"${disabled}${s.selected!=='current'?' disabled':''}>${esc(t('Review replacement'))}</button></div><p class="fine">${esc(t('Retained copies can be exported. Only the saved sync safety copy can replace this book here.'))}</p>`:`<p>${esc(t('No saved safety copies on this device.'))}</p>`}`}</div><p class="fine">${esc(t('Cancel stops preparation. Saving or replacement already started may finish.'))}</p><button class="btn ghost" data-safety-action="close">${esc(t('Close'))}</button>`;}
 function side(s,row,key){const value=row[key],book=key==='before'?s.review.before:s.review.after;if(value===null)return '<p>'+esc(t('Not present'))+'</p>';const accounts=new Map(book.accounts.map(a=>[a.id,a])),account=accounts.get(value.accountId),currency=value.currency||account?.currency||'MYR';const fields=[];for(const field of ['name','merchant','date','type'])if(typeof value[field]==='string')fields.push([t({name:'Name',merchant:'Merchant',date:'Date',type:'Type'}[field]),value[field]]);for(const field of ['amount','opening'])if(Number.isSafeInteger(value[field]))fields.push([t(field==='amount'?'Amount':'Opening balance'),currency+' '+(value[field]/100).toFixed(2)]);if(account)fields.push([t('Account'),account.name]);return '<dl>'+fields.map(([label,v])=>'<dt class="fine">'+esc(label)+'</dt><dd>'+esc(v)+'</dd>').join('')+'</dl><details'+(!fields.length?' open':'')+'><summary>'+esc(t('All fields'))+'</summary><pre tabindex="0">'+esc(JSON.stringify(value,null,2))+'</pre></details>';}
 function review(s){const rows=s.rows,pages=Math.max(1,Math.ceil(rows.length/10)),labels={accounts:'Accounts',tx:'Entries',recurring:'Regular payments',receipts:'Receipt photos',kv:'Book settings'};return `<h3>${esc(t('Replace this book'))}</h3><p>${esc(t('This replaces all entries, accounts, receipt photos and book settings with the selected copy. PIN, language and device preferences stay on this device.'))}</p><p class="fine">${esc(t('The current book and source copy will be retained inside Tally.'))}</p><p class="fine">${esc(t('{0} added · {1} changed · {2} deleted',rows.filter(r=>r.before===null).length,rows.filter(r=>r.before!==null&&r.after!==null).length,rows.filter(r=>r.after===null).length))}</p><section class="safety-review" aria-label="${esc(t('Review changes'))}">${rows.slice(s.page*10,(s.page+1)*10).map(row=>`<article><h4>${esc(t(labels[row.kind]))}: ${esc(row.after?.merchant||row.after?.name||row.before?.merchant||row.before?.name||row.id)}</h4><div class="grid2">${['before','after'].map(key=>`<div><h5>${esc(t(key==='before'?'Current book':'Selected copy'))}</h5>${side(s,row,key)}</div>`).join('')}</div></article>`).join('')||`<p>${esc(t('No changes on this device.'))}</p>`}</section><nav class="row2" aria-label="${esc(t('Review pages'))}"><button class="btn ghost" data-safety-page="${s.page-1}"${s.page===0||s.busy?' disabled':''}>${esc(t('Previous'))}</button><button class="btn ghost" data-safety-page="${s.page+1}"${s.page===pages-1||s.busy?' disabled':''}>${esc(t('Next'))}</button></nav><p class="fine">${esc(t('Page {0} of {1}',s.page+1,pages))}</p><label class="safety-consent"><input type="checkbox" data-safety-consent${s.confirmed?' checked':''}${s.busy||s.seen.size!==pages?' disabled':''}>${esc(t('I reviewed every page and want to replace this book.'))}</label><button class="btn danger" data-safety-action="replace"${s.busy||!s.confirmed||s.seen.size!==pages?' disabled':''}>${esc(t('Replace this book'))}</button><button class="btn ghost" data-safety-action="back"${s.busy?' disabled':''}>${esc(t('Back to copies'))}</button>`;}
 function paint(s){if(current(s)){const active=doc.activeElement;if(active&&s.el.contains(active)){for(const key of ['safetyAction','safetyConsent','safetySelect','safetyPage'])if(Object.hasOwn(active.dataset,key)){const attr=key.replace(/[A-Z]/g,c=>'-'+c.toLowerCase());s.focus='[data-'+attr+'="'+active.dataset[key]+'"]';break;}}const holder=doc.createElement('template');holder.innerHTML=html(s);s.el.querySelector('[data-safety-content]').innerHTML=holder.content.querySelector('[data-safety-content]').innerHTML;s.el.querySelector('[data-safety-status]').textContent=s.status;s.el.setAttribute('aria-busy',String(s.busy));const target=s.focus&&s.el.querySelector(s.focus);if(target&&!target.disabled)target.focus({preventScroll:true});}}
 async function run(s,action){if(!current(s)||s.busy)return false;s.busy=true;paint(s);await new Promise(r=>setTimeout(r,0));if(!current(s))return false;try{
  if(action==='list'){const copies=await s.operations.access.list();if(!current(s))return false;if(!Array.isArray(copies)||copies.some(r=>!ids.includes(r.id))||new Set(copies.map(r=>r.id)).size!==copies.length)throw Error('SELECTOR');s.copies=copies;s.selected=copies[0]?.id??null;s.status='';}
  if(action==='export'){const id=s.selected;if(!ids.includes(id))return false;const result=await s.operations.exporter.save({id,format:'zip'},mode==='native'?{mode,saveToDevice:async prepared=>nativeSaveSucceeded(await saveToDevice(prepared))}:{mode,requestDownload});if(!current(s))return false;s.status=t(({saved:'Backup saved', 'not-saved':'Backup was not saved','download-requested':'Download requested. Check your downloads.', 'not-requested':'Download was not requested'})[result.status]||'Backup was not saved');}
  if(action==='review'){if(s.selected!=='current')return false;progress(s,{stage:'review'});const plan=await s.operations.restore.prepare();if(!current(s))return false;if(plan.schema!=='tally.safety-restore/1'||typeof plan.token!=='string'||typeof plan.reviewHash!=='string'||plan.generation!==s.generation)throw Error('STALE');s.review=structuredClone(plan);s.rows=replacementRows(s.review.before,s.review.after);s.page=0;s.seen=new Set([0]);s.confirmed=false;s.status='';}
  if(action==='replace'){if(!s.review||!s.confirmed||s.seen.size!==Math.max(1,Math.ceil(s.rows.length/10)))return false;const {token,reviewHash}=s.review;s.review=null;progress(s,{stage:'replace'});const result=await s.operations.restore.restore({token,reviewHash,replace:true});if(!current(s))return false;s.status=t(result.status==='restored'?'Book replaced':'Book replaced. Reopen Tally to refresh.');}
 }catch(error){if(current(s)){s.review=null;s.confirmed=false;s.status=t(error.code==='LOSSY_FORMAT'?'This copy has fields that cannot be exported safely. Nothing was saved.':error.code==='RETAINED_COPY_EXISTS'?'Earlier recovery copies already exist. Replacement is unavailable; you can export the saved copies.':error.code==='CANCELLED'?'Preparation cancelled.':error.code==='STALE'?'This book changed. Close and reopen safety copies.':'Safety copy operation failed. Nothing was confirmed.');if(error.code==='LOSSY_FORMAT'&&Array.isArray(error.paths))s.status+=' '+error.paths.slice(0,20).join(', ');}}finally{if(current(s)){s.busy=false;paint(s);}}return true;}
 async function open(){if(!permitted())return false;cancel();const s={generation:getGeneration(),copies:[],selected:null,status:t('Reading safety copy'),busy:false,review:null,confirmed:false,page:0,seen:new Set()};session=s;try{s.operations=createOperations({authorized:()=>current(s),onProgress:event=>progress(s,event)});}catch{session=null;return false;}s.el=openSheet('<div data-safety-root>'+html(s)+'</div>',{label:t('Saved safety copies'),onClose:()=>{if(session===s)cancel();}});s.el.addEventListener('click',e=>{const button=e.target.closest('button');if(!button||button.disabled||!current(s))return;const action=button.dataset.safetyAction;if(action==='close'){cancel();return;}if(s.busy)return;if(button.dataset.safetyPage!==undefined&&s.review){const page=Number(button.dataset.safetyPage),pages=Math.max(1,Math.ceil(s.rows.length/10));if(Number.isInteger(page)&&page>=0&&page<pages){s.page=page;s.seen.add(page);paint(s);}return;}if(action==='back'){s.operations.restore.cancel();s.review=null;s.confirmed=false;paint(s);return;}if(['export','review','replace'].includes(action))void run(s,action);});s.el.addEventListener('change',e=>{if(!current(s)||s.busy)return;if(e.target.matches('[data-safety-select]')&&ids.includes(e.target.value)){s.selected=e.target.value;paint(s);}if(e.target.matches('[data-safety-consent]')){s.confirmed=e.target.checked===true;paint(s);}});s.hidden=()=>{if(doc.hidden)cancel();};s.replaced=()=>cancel();s.leave=()=>cancel();s.stopPrivacy=onPrivacyChange(v=>{if(v!==false)cancel();});doc.addEventListener('visibilitychange',s.hidden);doc.addEventListener('tally:book-replaced',s.replaced);win.addEventListener('pagehide',s.leave);await run(s,'list');return current(s);}
 return Object.freeze({available:permitted,open,cancel,close(){closed=true;cancel();}});
}
