import {writeFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
export async function runScenarios({pages,pair,click,check,qa}){
 const roles=['computer','phone'],action=a=>'[data-main-sync="'+a+'"]';
 async function rows(){return Promise.all(roles.map(r=>pages[r].evaluate(async()=>{const db=await import('/js/db.js');return (await db.all('tx')).sort((a,b)=>a.id.localeCompare(b.id));})));}
 async function closeBoth(){for(const r of roles){const p=pages[r],b=p.locator('.sync-sheet [data-act="sheet-close"]').last();if(await b.count())await b.click();await p.waitForFunction(()=>!document.querySelector('.scrim:not(.out)'));}}
 async function settings(){for(const r of roles){await pages[r].locator('a[href="#/settings"]').click();await pages[r].locator('[data-act="book-sync-open"]').waitFor();}}
 async function syncLinked({conflict=false}={}){await settings();await pair(false);for(const r of roles)await click(r,action('inspect'));for(const r of roles){await pages[r].locator(action('backup')).waitFor();await click(r,action('backup'));}for(const r of roles)await click(r,action('refresh'));if(conflict){for(const r of roles)await pages[r].waitForFunction(()=>document.querySelector('.sync-sheet')?.textContent.includes('Both books have changes that need review.'));return;}for(const r of roles){try{await pages[r].locator(action('approve')+':enabled').waitFor({timeout:5000});}catch(error){const proof=await Promise.all(roles.map(async role=>({role,...await pages[role].evaluate(()=>({phase:document.querySelector('[data-main-sync-phase]')?.dataset.mainSyncPhase,text:document.querySelector('.sync-sheet')?.innerText,buttons:[...document.querySelectorAll('[data-main-sync]')].map(b=>({action:b.dataset.mainSync,disabled:b.disabled}))}))})));await mkdir(qa,{recursive:true});await writeFile(qa+'/linked-failure.json',JSON.stringify(proof,null,2));throw error;}await click(r,action('approve'));}await click('computer',action('refresh'));await pages.computer.locator(action('coordinate')+':enabled').waitFor();await click('computer',action('coordinate'));for(const p of Object.values(pages))try{await p.waitForFunction(()=>document.querySelector('.sync-sheet')?.textContent.includes('Both books are up to date.'),null,{timeout:5000});}catch(error){const proof=await Promise.all(roles.map(async role=>({role,...await pages[role].evaluate(async()=>({ownedFailure:globalThis.__ownedCommitFailure,view:__ownedRuntime.getPairingView(),controller:__ownedRuntime.controller()?.state(),text:document.querySelector('.sync-sheet')?.innerText,local:(await(await import('/js/db.js')).getKv('offlineSync'))}))})));for(const x of proof)if(x.view?.pairing)x.view.pairing={manualRole:x.view.pairing.manualRole};await mkdir(qa,{recursive:true});await writeFile(qa+'/commit-failure.json',JSON.stringify(proof,null,2));throw error;}}
 async function add(r,merchant,amount){const p=pages[r];await p.locator('a[href="#/activity"]').click();await p.locator('.view-activity [data-act="tx-new"]').click();await p.locator('#tx-amt').fill(amount);await p.locator('#tx-merchant').fill(merchant);await p.locator('[data-act="tx-cat"][data-c="dining"]').click();await p.locator('[data-act="tx-save"]').click();await p.waitForFunction(name=>!document.querySelector('#tx-amt')&&document.querySelector('.view-activity')?.textContent.includes(name),merchant);return p.evaluate(async name=>(await(await import('/js/db.js')).all('tx')).find(t=>t.merchant===name).id,merchant);}
 async function edit(r,id,amount){const p=pages[r];await p.locator('a[href="#/activity"]').click();await p.locator('[data-act="tx-open"][data-id="'+id+'"]').click();await p.locator('#tx-amt').fill(amount);await p.locator('[data-act="tx-save"]').click();await p.waitForFunction(()=>!document.querySelector('#tx-amt'));}
 await closeBoth();const pcId=await add('computer','Owned computer offline','7.11'),phoneId=await add('phone','Owned phone offline','8.22');const offline=await rows();check('disconnected ordinary full Tally UI independently saves both offline expenses',offline[0].some(t=>t.id===pcId)&&!offline[0].some(t=>t.id===phoneId)&&offline[1].some(t=>t.id===phoneId)&&!offline[1].some(t=>t.id===pcId));
 await syncLinked();const bidir=await rows();check('fresh pairing+separate sharing consent reconciles both independent additions over actual RTC',bidir.every(a=>a.some(t=>t.id===pcId)&&a.some(t=>t.id===phoneId))&&JSON.stringify(bidir[0])===JSON.stringify(bidir[1]));
 const learned=await Promise.all(roles.map(r=>pages[r].evaluate(async()=>{const db=await import('/js/db.js'),engine=await import('/js/engine.js'),rules=await db.getKv('rules');return [rules?.[engine.itemKey('Owned computer offline')],rules?.[engine.itemKey('Owned phone offline')]];})));check('independent new merchant learning survives on both books without suppressing either rule',learned.every(v=>v[0]==='dining'&&v[1]==='dining'));
 await closeBoth();const p=pages.computer;await p.locator('a[href="#/activity"]').click();await p.locator('[data-act="tx-open"][data-id="'+pcId+'"]').click();await p.locator('[data-act="tx-del"]').click();await p.locator('[data-x="yes"]').click();await p.waitForFunction(()=>!document.querySelector('#tx-amt'));
 const photoProof=await pages.phone.evaluate(async id=>{const st=await import('/js/state.js'),core=await import('/js/book-sync/sync-core.mjs'),canvas=document.createElement('canvas');canvas.width=31;canvas.height=19;const c=canvas.getContext('2d');c.fillStyle='#d03060';c.fillRect(0,0,31,19);const blob=await new Promise(r=>canvas.toBlob(r,'image/png')),row=structuredClone(st.S.tx.find(t=>t.id===id)),photoId='owned-offline-new-photo';if(!(await st.savePhoto(photoId,blob,{generation:st.bookGeneration()})))throw Error('photo did not save');await st.saveTx({...row,receiptId:photoId},{expected:row});return {id:photoId,sha:await core.sha256(new Uint8Array(await blob.arrayBuffer()))};},phoneId);
 await syncLinked();const delRows=await rows(),photoHashes=await Promise.all(roles.map(r=>pages[r].evaluate(async id=>{const db=await import('/js/db.js'),core=await import('/js/book-sync/sync-core.mjs'),r=await db.get('receipts',id);return core.sha256(new Uint8Array(await r.blob.arrayBuffer()));},photoProof.id)));check('unilateral ordinary-UI deletion and opposite-device new PNG reference both reconcile without resurrection or byte loss',delRows.every(a=>!a.some(t=>t.id===pcId)&&a.some(t=>t.id===phoneId&&t.receiptId===photoProof.id))&&photoHashes.every(h=>h===photoProof.sha));
 await closeBoth();await settings();const beforeCancel=await rows();await pair(false);for(const r of roles)await click(r,action('inspect'));await closeBoth();check('cancel before backup/review leaves both financial books unchanged',JSON.stringify(await rows())===JSON.stringify(beforeCancel));
 await settings();await pair(false);await pages.computer.evaluate(async()=>{const st=await import('/js/state.js'),lock=await import('/js/lock.js');await st.setSetting('lock',await lock.makeLock('1234'));globalThis.ownedGateDone=false;lock.gate().then(()=>ownedGateDone=true);});await pages.computer.locator('#lock-pin').waitFor();await pages.phone.waitForFunction(()=>!document.querySelector('[data-main-sync="inspect"]'));check('actual public PIN gate synchronously tears down approved RTC/sharing UI',await pages.computer.locator('.sync-sheet').count()===0);const lockedBefore=await rows();await pages.computer.locator('#lock-pin').fill('0000');await pages.computer.waitForFunction(()=>document.querySelector('#lock-pin')?.getAttribute('aria-invalid')==='true'||document.querySelector('.lock .err')?.textContent);check('incorrect PIN cannot reconnect or revive sharing',await pages.computer.locator('.sync-sheet').count()===0);await pages.computer.locator('#lock-pin').fill('1234');await pages.computer.waitForFunction(()=>ownedGateDone===true);check('valid real unlock keeps both books unchanged and requires fresh pairing/consents',JSON.stringify(await rows())===JSON.stringify(lockedBefore));await closeBoth();
 await edit('computer','original','6.51');await edit('phone','original','6.72');const conflictedBefore=await rows();await syncLinked({conflict:true});check('same-entry opposing edits produce read-only conflict with no Sync control or automatic overwrite',await pages.computer.locator('[data-main-sync="coordinate"]').count()===0&&JSON.stringify(await rows())===JSON.stringify(conflictedBefore));await closeBoth();
}
