import { chromium, expect } from 'playwright/test';
import { createServer } from 'node:http';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { resolve, extname, sep } from 'node:path';
import { spawnSync } from 'node:child_process';
import assert from 'node:assert/strict';

const root='D:/tally-native', oldRoot='C:/Users/user/claude-sandbox/mm';
const out='D:/tally-android/verification/migration';
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.woff2':'font/woff2','.png':'image/png','.svg':'image/svg+xml','.json':'application/json'};
const checks=[],errors=[],limitations=[];
let success=false,failure=null;
const checked=(name)=>{checks.push(name);console.log('PASS',name);};
async function serve(old=false){
 const cache=new Map();const server=createServer(async(req,res)=>{
  try{const name=decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\//,'')||'index.html';
   if(!/^(index\.html|manifest\.webmanifest|build\.txt|(?:js|css|fonts|icons|img|vendor)\/[\w./-]+)$/.test(name)||name.includes('..'))throw Error('Not a public asset');
   let data;if(old){if(!cache.has(name)){const p=spawnSync('git',['show','HEAD:'+name],{cwd:oldRoot,maxBuffer:8*1024*1024});if(p.status)throw Error('Not tracked');cache.set(name,p.stdout);}data=cache.get(name);}else{const p=resolve(root,name);if(!p.startsWith(resolve(root)+sep))throw Error();data=await readFile(p);}
   if(old&&name==='js/views/setup.js'&&process.env.MIGRATION_PATCHED_EXPORT==='1')data=await readFile(resolve(oldRoot,name));
   res.setHeader('Content-Type',mime[extname(name)]||'application/octet-stream');res.setHeader('Cache-Control','no-store');res.end(data);
  }catch{res.writeHead(404);res.end();}
 });await new Promise(r=>server.listen(0,'127.0.0.1',r));return server;
}
function nativeStub(){
 window.__saveMode='saved';window.__cache={};window.__saved=[];
 const addListener=async()=>({remove(){}});
 window.Capacitor={isNativePlatform:()=>true,Plugins:{App:{addListener,getInfo:async()=>({id:'migration.simulated',version:'1.13.0',build:'3'})},
 Filesystem:{writeFile:async({path,data})=>{window.__cache[path]=data;},appendFile:async({path,data})=>{window.__cache[path]+=data;},deleteFile:async({path})=>{delete window.__cache[path];},getUri:async({path})=>({uri:path})},
 TallyNative:{addListener,takeShared:async()=>({files:[]}),reserveOutput:async({name})=>{const path='out/'+crypto.randomUUID()+'-'+name;return{uri:"file:///"+path,path};},releaseOutput:async()=>{},releaseShared:async()=>{},openExternal:async()=>{},saveToDevice:async args=>{if(window.__saveMode==='failed')throw Error('Simulated save failure');if(window.__saveMode==='cancelled')return{cancelled:true};window.__saved.push({name:args.name,data:window.__cache[args.uri.replace("file:///","")]});return{cancelled:false};}}}};
}
// Keep both isolated books on the same day across a midnight run. Otherwise a
// legitimate due bill on reload changes the fixture independently of migration.
async function ready(page,url){await page.goto(url+'/?app&today=2026-10-03&now=12:00');await page.locator('.welcome, .view-home, .view-settings').first().waitFor();}
async function snapshot(page){return page.evaluate(async()=>{const s=await import('/js/state.js'),e=await import('/js/engine.js');const pick=({accounts,tx,recurring,kv})=>({accounts:[...accounts].sort((a,b)=>a.id.localeCompare(b.id)),tx:[...tx].sort((a,b)=>a.id.localeCompare(b.id)),recurring:[...recurring].sort((a,b)=>a.id.localeCompare(b.id)),kv:Object.fromEntries(['budgets','rules','customCats','shopNames','itemNames','catColors','catIcons','goals','subcats','subRules'].map(k=>[k,kv[k]]))});return{data:pick(s.S),balances:e.balances(s.S.accounts,s.S.tx),settings:s.settings()};});}
async function clearSheets(page){await page.evaluate(async()=>{const ui=await import('/js/ui.js');while(ui.sheetOpen())ui.closeSheet();});}
async function importBackup(page,file,choice){
 await clearSheets(page);const picked=page.waitForEvent('filechooser');
 if(await page.locator('[data-act="restore-pick"]').count())await page.locator('[data-act="restore-pick"]').first().click();
 else await page.evaluate(async()=>{(await import('/js/views/setup.js')).act['restore-pick']();});
 await (await picked).setFiles(file);
 if(choice)await page.locator('.scrim:not(.out) [data-x="'+choice+'"]').click();
}
async function waitRows(page,n){await page.waitForFunction(async n=>(await import('/js/state.js')).S.tx.length===n,n);}
await mkdir(out,{recursive:true});const old=await serve(true),fresh=await serve();const oldUrl='http://127.0.0.1:'+old.address().port,newUrl='http://127.0.0.1:'+fresh.address().port;
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
const web=await browser.newContext({acceptDownloads:true,viewport:{width:390,height:844},serviceWorkers:'block'}),app=await browser.newContext({acceptDownloads:true,viewport:{width:390,height:844},serviceWorkers:'block'});
await app.addInitScript(nativeStub);await app.tracing.start({screenshots:true,snapshots:true});
const a=await web.newPage(),b=await app.newPage();for(const p of[a,b])p.on('pageerror',e=>errors.push(e.message));
try{
 await ready(a,oldUrl);await ready(b,newUrl);
 assert.equal((await snapshot(b)).data.tx.length,0);checked('Fresh native storage cannot automatically see the browser book');
 const emptyBook=await snapshot(b);await b.getByRole('button',{name:'Guide me',exact:true}).click();await expect(b.getByText('Step 1: Back up the website',{exact:true})).toBeVisible();assert.equal(await b.getByRole('link',{name:'Open old Tally',exact:true}).getAttribute('href'),'https://tallymy.github.io/?app');await b.getByRole('button',{name:'I have the backup file',exact:true}).click();await expect(b.getByText('Step 2: Restore here',{exact:true})).toBeVisible();await b.locator('.scrim:not(.out) [data-act="sheet-close"]').last().click();assert.deepEqual((await snapshot(b)).data,emptyBook.data);checked('Native guide names the actual backup and restore buttons; Later changes no book data');
 await b.getByRole('button',{name:"I'll do it myself",exact:true}).click();assert.equal(await b.locator('#migration-welcome').count(),0);assert.deepEqual((await snapshot(b)).data,emptyBook.data);await b.reload();await b.locator('#migration-welcome').waitFor();await b.locator('#migration-welcome').getByRole('button',{name:'Later',exact:true}).click();assert.equal(await b.locator('#migration-welcome').count(),0);assert.deepEqual((await snapshot(b)).data,emptyBook.data);checked('Do it myself and Later skip the native guide without touching expenses');
 await a.evaluate(async()=>{const s=await import('/js/state.js'),sample=(await import('/js/sample.js')).sampleData('2026-10-03');
  const clean=x=>{const{sample,...v}=x;return v;};await s.putAll({accounts:sample.accounts.map(clean),tx:sample.tx.map(clean),recurring:sample.recurring.map(clean),kv:{budgets:sample.budgets,goals:sample.goals,subcats:{dining:['Breakfast']},subRules:{kopitiam:['dining','Breakfast']},settings:{onboarded:true,tourDone:true,seenVersion:'1.12.5',lang:'en',theme:'light',textSize:115,myName:'Migration Test'}}});
  const canvas=document.createElement('canvas');canvas.width=80;canvas.height=120;const g=canvas.getContext('2d');g.fillStyle='#fff';g.fillRect(0,0,80,120);g.fillStyle='#000';g.fillText('Test receipt',5,30);const blob=await new Promise(r=>canvas.toBlob(r,'image/jpeg'));await s.savePhoto('migration_photo',blob);const tx=s.S.tx.find(x=>x.items?.length);await s.saveTx({...tx,receiptId:'migration_photo'});(await import('/js/app.js')).go('settings');});
 const source=await snapshot(a);assert.ok(source.data.tx.length>100);checked('Old released web code holds a realistic book with splits, itemised receipts, bills, budgets and settings');
 await a.locator('[data-act="backup"]').first().click();await expect(a.locator('#bk-photos')).toBeChecked();
 const dl=a.waitForEvent('download');await a.locator('[data-act="bk-save"]').click();const download=await dl;const photoPath=out+'/browser-backup.zip';await download.saveAs(photoPath);
 checked('Settings → Back up → Save downloads the actual photo backup');await a.screenshot({path:out+'/browser-backup-saved.png',fullPage:true});
 const inspected=await b.evaluate(async bytes=>{const io=await import('/js/io.js'),z=await io.unzip(Uint8Array.from(bytes).buffer,n=>n==='tally-backup.json'||n.startsWith('photos/'));const parsed=io.readBackup(new TextDecoder().decode(z['tally-backup.json']));return{parsed,photos:Object.keys(z).filter(n=>n.startsWith('photos/'))};},Array.from(await readFile(photoPath)));
 assert.equal(inspected.parsed.dropped,0);assert.equal(inspected.parsed.tx.length,source.data.tx.length);assert.equal(inspected.photos.length,1);
 if(!inspected.parsed.kv.subcats||!inspected.parsed.kv.subRules)limitations.push('Released 1.12.5 exporter omits subcategories/rules; a pre-migration website exporter update is needed to retain these. Older files cannot restore fields they do not contain.');
 if(process.env.MIGRATION_PATCHED_EXPORT==='1'){assert.deepEqual(inspected.parsed.kv.subcats,source.data.kv.subcats);assert.deepEqual(inspected.parsed.kv.subRules,source.data.kv.subRules);checked('Patched pre-migration website exporter preserves subcategories and matching rules');}
 await expect(b.locator('[data-act="restore-pick"]').first()).toBeVisible();await importBackup(b,photoPath);await waitRows(b,source.data.tx.length);
 await b.waitForFunction(async()=>!!await(await import('/js/state.js')).getPhoto('migration_photo'));
 await b.waitForFunction(async()=>(await import('/js/state.js')).settings().onboarded===true);
 console.log('Settings comparison',JSON.stringify({exported:inspected.parsed.settings,source:source.settings,destination:(await snapshot(b)).settings}));
 const migrated=await snapshot(b);assert.deepEqual(migrated.balances,source.balances);assert.equal(migrated.data.accounts.length,source.data.accounts.length);assert.equal(migrated.data.recurring.length,source.data.recurring.length);
 assert.deepEqual(migrated.data.tx,inspected.parsed.tx.sort((x,y)=>x.id.localeCompare(y.id)));assert.deepEqual(migrated.data.kv.budgets,inspected.parsed.kv.budgets);assert.equal(migrated.settings.theme,'light');assert.equal(migrated.settings.textSize,115);assert.equal(migrated.settings.myName,'Migration Test');
 checked('Welcome → Restore a Tally backup → Choose file preserves every exported transaction, balance, bill, budget, setting and receipt photo');await b.screenshot({path:out+'/native-restored.png',fullPage:true});
 await b.reload();await b.locator('h1').first().waitFor();await waitRows(b,source.data.tx.length);assert.deepEqual((await snapshot(b)).data,migrated.data);checked('Reload/cold-start simulation preserves the restored book');
 const badPath=out+'/invalid.json';await writeFile(badPath,'{"app":"Not Tally","tx":[]}');await importBackup(b,badPath);await expect(b.locator('#imp-err')).toContainText('not a Tally backup');assert.deepEqual((await snapshot(b)).data,migrated.data);checked('Wrong-format backup changes nothing');
 const futurePath=out+'/future.json';await writeFile(futurePath,JSON.stringify({...inspected.parsed,app:'tally',v:999}));
 // Use the real exported marker, not an invented test marker.
 const backupJSON=await a.evaluate(async()=>{const io=await import('/js/io.js'),s=await import('/js/state.js');return io.makeBackup(s.S);});await writeFile(futurePath,JSON.stringify({...JSON.parse(backupJSON),v:999}));
 await importBackup(b,futurePath);await expect(b.locator('#imp-err')).toContainText('newer version');assert.deepEqual((await snapshot(b)).data,migrated.data);checked('Backup from a newer unsupported version changes nothing');
 await importBackup(b,photoPath,'no');assert.deepEqual((await snapshot(b)).data,migrated.data);checked('Cancel restore leaves the existing book intact');
 for(let i=0;i<5;i++){await importBackup(b,photoPath,'merge');await b.waitForFunction(()=>!document.querySelector('.scrim:not(.out) [data-x="merge"]'));assert.deepEqual((await snapshot(b)).data,migrated.data);}
 checked('Five repeated merge restores create no duplicates or balance drift');
 await b.evaluate(async()=>{(await import('/js/app.js')).go('settings');});await b.getByRole('button',{name:'Migration help',exact:true}).click();await expect(b.getByText('Step 1: Back up the website',{exact:true})).toBeVisible();await clearSheets(b);checked('Migration guide remains available in Settings after skipping');
 await a.evaluate(async()=>{const ui=await import('/js/ui.js');while(ui.sheetOpen())ui.closeSheet();(await import('/js/views/setup.js')).act.backup();});
 await a.locator('.scrim:not(.out) details.more-cats summary').click();await a.locator('#bk-pass').fill('migration-test-password');const protectedDownload=a.waitForEvent('download');await a.locator('[data-act="bk-save"]').click();const protectedPath=out+'/protected.locked.json';await(await protectedDownload).saveAs(protectedPath);
 await importBackup(b,protectedPath);await b.locator('.scrim:not(.out) #rp-pass').fill('wrong-password');await b.locator('.scrim:not(.out) [data-x="ok"]').click();await expect(b.getByText('Wrong password, or the file was changed.',{exact:true}).first()).toBeVisible();assert.deepEqual((await snapshot(b)).data,migrated.data);checked('Wrong backup password changes nothing');
 await importBackup(b,protectedPath);await b.locator('.scrim:not(.out) [data-x="no"]').click();assert.deepEqual((await snapshot(b)).data,migrated.data);checked('Cancelling password entry changes nothing');
 await importBackup(b,protectedPath);await b.locator('.scrim:not(.out) #rp-pass').fill('migration-test-password');await b.locator('.scrim:not(.out) [data-x="ok"]').click();await b.locator('.scrim:not(.out) [data-x="merge"]').click();await b.waitForFunction(()=>!document.querySelector('.scrim:not(.out) [data-x="merge"]'));assert.deepEqual((await snapshot(b)).data,migrated.data);checked('Protected photo backup restores with correct password without duplicates');
 await b.evaluate(()=>{window.__originalPut=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value,...rest){if(this.name==='receipts')throw new DOMException('Simulated full storage','QuotaExceededError');return window.__originalPut.call(this,value,...rest);};});
 const photoBefore=await b.evaluate(async()=>Array.from(new Uint8Array(await(await(await import('/js/state.js')).getPhoto('migration_photo')).arrayBuffer())));
 await importBackup(b,photoPath,'replace');await expect(b.getByText('Simulated full storage',{exact:true}).first()).toBeVisible();await b.evaluate(()=>{IDBObjectStore.prototype.put=window.__originalPut;});assert.deepEqual((await snapshot(b)).data,migrated.data);assert.deepEqual(await b.evaluate(async()=>Array.from(new Uint8Array(await(await(await import('/js/state.js')).getPhoto('migration_photo')).arrayBuffer()))),photoBefore);checked('Full storage during photo restore rolls back ledger and photos together');
 await b.evaluate(async()=>{const s=await import('/js/state.js');await s.saveAccount({id:'only_local',name:'Local only',kind:'cash',opening:12345});});await importBackup(b,photoPath,'no');assert.ok((await snapshot(b)).data.accounts.some(x=>x.id==='only_local'));await importBackup(b,photoPath,'replace');await b.waitForFunction(async()=>!(await import('/js/state.js')).S.accounts.some(x=>x.id==='only_local'));assert.deepEqual((await snapshot(b)).balances,source.balances);checked('Replace removes only the isolated destination book; browser source remains intact');
 await clearSheets(b);await b.evaluate(async()=>{(await import('/js/views/setup.js')).act.backup();window.__saveMode='cancelled';});const lastBackup=await b.evaluate(async()=>(await import('/js/state.js')).S.kv.lastBackup);await b.locator('[data-act="bk-save"]').click();await b.waitForFunction(()=>!document.querySelector('[data-act="bk-save"]')?.disabled);
 assert.equal(await b.evaluate(async()=>(await import('/js/state.js')).S.kv.lastBackup),lastBackup,'Cancelled Save as must not mark a backup as saved');assert.equal(await b.evaluate(()=>window.__saved.length),0);checked('Cancelled native Save as does not claim a backup exists');
 await b.evaluate(()=>window.__saveMode='failed');await b.locator('[data-act="bk-save"]').click();await expect(b.getByText('Could not save. Your phone may be out of space.',{exact:true}).first()).toBeVisible();assert.equal(await b.evaluate(async()=>(await import('/js/state.js')).S.kv.lastBackup),lastBackup);checked('Failed native Save as displays an error and does not mark a backup');
 await b.evaluate(()=>window.__saveMode='saved');await b.locator('[data-act="bk-save"]').click();await b.waitForFunction(()=>window.__saved.length===1);checked('Successful native Save as awaits confirmation');
 const guideContext=await browser.newContext({acceptDownloads:true,serviceWorkers:'block'});const guide=await guideContext.newPage();try{await ready(guide,newUrl);await guide.evaluate(async()=>{const s=await import('/js/state.js');await s.saveAccount({id:'guide',name:'Guide test',kind:'cash',opening:1000});await s.setSetting('onboarded',true);await s.setSetting('tourDone',true);(await import('/js/app.js')).go('settings');});const unchanged=await snapshot(guide);await guide.getByRole('button',{name:'Migration help',exact:true}).click();await guide.locator('.scrim:not(.out)').getByRole('button',{name:'Later',exact:true}).click();assert.deepEqual((await snapshot(guide)).data,unchanged.data);await guide.getByRole('button',{name:'Migration help',exact:true}).click();await guide.locator('.scrim:not(.out) [data-act="migration-backup"]').click();await expect(guide.locator('[data-act="bk-save"]')).toBeVisible();const file=guide.waitForEvent('download');await guide.locator('[data-act="bk-save"]').click();await(await file).saveAs(out+'/guided-backup.json');await expect(guide.getByText('Step 2: Find the file',{exact:true})).toBeVisible();await guide.getByRole('button',{name:"I've found the file",exact:true}).click();await expect(guide.getByText('Step 3: Restore in the app',{exact:true})).toBeVisible();assert.deepEqual((await snapshot(guide)).data,unchanged.data);await guide.screenshot({path:out+'/browser-guided-restore.png',fullPage:true});checked('Browser guide opens real backup buttons, requires manual file check and preserves source data');}finally{await guideContext.close();}
 const busy=await browser.newContext({serviceWorkers:'block'});await busy.addInitScript(nativeStub);const heavy=await busy.newPage();try{await ready(heavy,newUrl);const book=await heavy.evaluate(async()=>{const s=await import('/js/state.js');const tx=Array.from({length:2000},(_,i)=>({id:'stress_'+i,accountId:'stress_bank',amount:i+1,type:'expense',date:'2026-09-01',category:'other',merchant:'Synthetic '+i,source:'quick',createdAt:Date.now()+i}));await s.putAll({accounts:[{id:'stress_bank',name:'Stress test',kind:'bank',opening:10000000}],tx,kv:{settings:{onboarded:true,tourDone:true,seenVersion:'1.13.0'}}});(await import("/js/app.js")).go("home");return{rows:s.S.tx.length,total:(await import('/js/engine.js')).balances(s.S.accounts,s.S.tx).total};});
 for(let i=0;i<3;i++){await heavy.reload();await heavy.locator(".view-home").waitFor();await heavy.waitForFunction(async()=>{const s=await import("/js/state.js");return s.S.tx.length===2000&&s.S.accounts.length===1;});const observed=await snapshot(heavy);if(observed.balances.total!==book.total)console.log("Large-book mismatch",JSON.stringify({accounts:observed.data.accounts,total:observed.balances,first:observed.data.tx[0]}));assert.equal(observed.balances.total,book.total);assert.equal(observed.data.tx.length,book.rows);}checked('2,000-entry book survives three reloads without lost rows or balance drift');}finally{await busy.close();}
 assert.deepEqual((await snapshot(a)).balances,source.balances);checked('Migration never deletes or alters the browser source book');
 assert.deepEqual(errors,[]);checked('No uncaught application errors');success=true;
}catch(e){failure=e.message;await b.screenshot({path:out+'/failure.png',fullPage:true}).catch(()=>{});console.error(e);process.exitCode=1;
}finally{await writeFile(out+'/results.json',JSON.stringify({success,failure,passed:checks.length,checks,limitations,errors,simulated:true,nativeFilePicker:'mocked; real UI export/import and IndexedDB used',sourceCommit:spawnSync('git',['rev-parse','HEAD'],{cwd:oldRoot,encoding:'utf8'}).stdout.trim()},null,2));await app.tracing.stop({path:out+'/trace.zip'});await browser.close();await Promise.all([new Promise(r=>old.close(r)),new Promise(r=>fresh.close(r))]);}
